# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export PATH

#Borrow yuhuangl
export CPPFLAGS="-I/home/yuhuangl/opt/include -I/home/yuhuangl/opt/include/ncurses"
export LDFLAGS='-L/home/yuhuangl/opt/lib'
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/opt/lib
